'area: core':
- packages/turbo-module/**/*

'area: util':
- packages/util/**/*

'area: action':
- packages/action/**/*

'area: create-turbo-module':
- packages/create-turbo-module/**/*

'area: infra':
- ./.github/**/*
- ./turbo.json
