name: 'turbo-module action'
description: 'release and mange public npm packages'
author: 'whop team'
runs:
  using: 'node16'
  main: 'packages/action/out/index.js'
inputs:
  action:
    description: "The action to perform ('check', 'release', 'sync', 'update')"
    required: true
  token:
    description: "Github access token"
    required: true
  initial-commit:
    description: "Initial commit SHA to track for releases"
  published:
    description: "Indicates if the same workflow published a new release to npm, required for 'sync' action"
  version:
    description: "The current verison of the package. Required for 'release'"
  working-directory:
    description: "Subdirectory to operate in (for monorepos). Paths are relative to this directory."
    default: "."
  version-files:
    description: "JSON array of package.json paths to update when creating release PRs. All files will be updated to the same version."
    default: '["package.json"]'
  publish-packages:
    description: "JSON array of package paths to check for publishing. If not set, scans packages/* directory."
  prerelease-type:
    description: "Prerelease identifier to use (e.g., 'canary', 'beta')"
    default: "canary"
  base-branch:
    description: "Base branch for PRs and releases"
    default: "main"
  max-changelog-commits:
    description: "Maximum commits to scan for changelog generation (0 = unlimited)"
    default: "100"
  pr-title-prefix:
    description: "Prefix for release PR titles (e.g., '[Embedded SDK]')"
    default: ""
