name: 'turbo-module action'
description: 'release and mange public npm packages'
author: 'whop team'
runs:
  using: 'node16'
  main: 'packages/action/index.js'
inputs:
  action:
    description: "The action to perform ('check', 'release', 'sync', 'update')"
    required: true
  token:
    description: "Github access token, 'update' requires access to the .gihub folder"
    required: true
  initial-commit:
    description: "Initial commit SHA to track for releases"
  published:
    description: "Indicates if the same workflow published a new release to npm, required for 'sync' action"
  version:
    description: "The current verison of the package. Required for 'release'"
