on:
  pull_request:
    types:
      - synchronize
      - opened

name: PR

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: whop

concurrency:
  group: pr-action-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  unimported:
    name: Check unimported
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: whopio/unimported-action@v0.0.1
        with:
          token: ${{ github.token }}
          projects: 'packages/action,packages/create-turbo-module,packages/turbo-module'

  install:
    name: Install node modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.5
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: pnpm
      - name: Install all packages
        run: pnpm install

  lint:
    name: Lint repository
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: pnpm
      - name: Install all packages
        run: pnpm install
      - name: Run eslint
        run: pnpx eslint@8.57.0 ./ --max-warnings 0

  build:
    name: Build packages
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: pnpm
      - name: Install all packages
        run: pnpm install
      - name: Build packages
        run: pnpm turbo build

  test:
    name: Test repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: pnpm
      - name: Install all packages
        run: pnpm install
      - name: Build packages
        run: pnpm turbo test
