on:
  push:
    branches:
      - tristan/split-up-packages-and-craete-action

name: Test some stuff

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with: 
          action: check
          token: ${{ github.token }}
